name: pytorch-segmentation
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.2.1
  - torchvision=0.17.1
  - numpy=1.26.4
  - pillow=11.3.0
  - pip
  - pip:
      - pytorch-lightning==2.2.1
      - python-dotenv==1.1.1
      - wandb==0.21.1
      - albumentations==2.0.8
      - opencv-python==4.12.0.88
      - pyyaml==6.0.2
      - torchmetrics==1.8.1
